# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-04-30 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBeconsult', '0002_auto_20200430_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(default=1, upload_to='/static/webBeconsult/img/'),
            preserve_default=False,
        ),
    ]
