# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-04-30 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBeconsult', '0007_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(null=True, upload_to='webBeconsult/img/uploads/empleados'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(null=True, upload_to='webBeconsult/img/uploads'),
        ),
    ]
