# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-04-30 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBeconsult', '0008_auto_20200430_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='employees',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
