# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-04-30 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webBeconsult', '0009_auto_20200430_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
