# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-05-04 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webBeconsult', '0011_auto_20200504_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='title',
            new_name='Titulo',
        ),
        migrations.RenameField(
            model_name='joboffer',
            old_name='title',
            new_name='Titulo',
        ),
    ]
