# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-05-06 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webBeconsult', '0015_auto_20200506_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
